### ISSUE TITLE
Performance increase

### ISSUE THREAD

**Issue by lucasavila00** [amiiit/pigeon-cluster#1]
Hi, @amiiit. Nice job! You mentioned you'd like to improve performance of this lib on the pigeon-maps thread.
One thing to do is to first check which items are within the bounds of the map and then "cluster" these ones. It gives immense performance increase when you are zooming in but changes nothing when you're zooming too high.
_On my project I set a zoom limit and then could make sure performance was OK at all times_
And you said you wanted to stop using supercluster, have you seen https://github.com/mourner/rbush? It's the underlying gears behind supercluster...

**Comment by amiiit** [comment]
Thanks mate. The first draft of this library was a naive implementation, meaning that for every render the whole data-structure was built. This is obviously not scalable.

I found out that building the data structure just once and for every time the markers change is what gives the performance boots, since retrieving the clusters from `supercluster` isn't an expensive operation. You can see I started to work on this on the branch [`feature/performance`](https://github.com/amiiit/pigeon-cluster/tree/feature/performance)

will update here when it's ready to merge

About replacing supercluster, there are a few things supercluster doesn't supply out of the box. I will create a seperate issue for that.

**Comment by amiiit** [comment]
Okay merged some updates for performance. I didn't work over PR for this because I feel this is still quite an early stage for this repo.

See #2 for alternative for supercluster
